resolver: lts-14.27
packages:
- ./.
extra-deps:
- inline-c-cpp-0.4.0.2
- inline-c-0.9.0.0
- jose-0.8.2.0
- servant-auth-0.3.2.0
- servant-auth-client-0.4.0.0
- servant-auth-server-0.4.5.0
- servant-auth-swagger-0.2.10.0
